### PR TITLE
Added functionality for timeing out, and then reconnecting after  (#24)

### PR DESCRIPTION
**Pull request by jessebarton**
Hey! Once again appreciate the opportunity to work on this and learn a little. I have added the command line flag as well as the timeout functionality i'm trying now to figure out the best way to implement how it reconnects. I've tried a few things that didn't work as expected would you have any input for me on the best way to implement that? Appreciate any feedback!

### CODE REVIEW

**Comment by jessebarton** [comment]
Submitted the first portion of this pull request working on getting the reconnect portion added.

**Comment by davrodpin** [comment]
Hi @jessebarton,

First you will need a retry logic when `error` is signalized through `done` channel (please refer to `Tunnel.Start()`). 
Then you would need to handle the case where another `error` is sent. That could be caused because the connection retry failed or any another issue. 
In this case, since mole had already re-tried to connect to the ssh server, the code should wait for 10 seconds before trying again.
Remember that after waiting for the `-reconnect-after` period, the retry logic should be reset.

Please note this is different than a channel timeout approach.

Hope this help :)

**Comment by jessebarton** [comment]
@davrodpin That does help for sure. Would i do this retry logic inside of the select statement? Or would this be more suited to be placed inside of the anonymous function that is inside the start function? Thanks!

**Comment by davrodpin** [comment]
> @davrodpin That does help for sure. Would i do this retry logic inside of the select statement? Or would this be more suited to be placed inside of the anonymous function that is inside the start function? Thanks!

Let's see how the code will look if implemented inside the `select/case` statement.
I believe we're gonna extract as a function before it change gets merged, but let's do baby steps :)
Another advice is that `Tunnel.done` would probably need to be changed to contain not only the error, but also the local connection mostly because the retry logic will need to call `Tunnel.forward`.

**Comment by davrodpin** [comment]
Closing due to inactivity. PR #95 replaces it.

**Pull request closed without merging**
