### PR TITLE
Handle encrypted keys

### LINKED ISSUE #30: error generating ssh client config: ssh: cannot decode encrypted private keys
## Expected Behavior

Requests to localhost:3389 should be forward to remote:8888, 

## Current Behavior

localhost:3389 can't be reached, and 
`ERRO[0002] error generating ssh client config: ssh: cannot decode encrypted private keys  tunnel="[local:127.0.0.1:3389, server:my.Server.I.P:myServerPort, remote:127.0.0.1:8888]"`

## Steps to Reproduce

1. In remote server, run `jupyter lab`, this will run the jupyter on port 8888.
2. Add the server information into **~/.ssh/config**:
```
Host myServer
  Hostname my.Server.I.P
  Port myServerPort
  User user
  IdentityFile ~/.ssh/id_rsa
```
3. Run `mole -v -local :3389 -remote :8888 -server myServer`.
4. Visit `http://localhost:3389/` in a browser.

The ssh-agent is running and I added the ssh key into the macOS keychain by `ssh-add -K ~/.ssh/id_rsa`. After the error, I remove it from the keychain by `ssh-add -d ~/.ssh/id_rsa`, but no luck. I also killed the ssh-agent process, still the same error.

Before mole, I use this ssh command: `ssh -N -p myServerPort devops@my.Server.I.P -L localhost:3389:localhost:8888` and it works fine.

### PR DESCRIPTION
**Pull request by akshaychhajed**
Prompts for passphrase when encrypted keys are detected

Fixes #30

### CODE REVIEW

**Comment by akshaychhajed** [comment]
@davrodpin thank you for your feedback. I am working on them.
New function involves user input. Any ideas how we can test them?

**Comment by akshaychhajed** [comment]
@davrodpin I have restructured the function and added test

**Comment by davrodpin** [comment]
> @davrodpin thank you for your feedback. I am working on them.
> New function involves user input. Any ideas how we can test them?

The function handling the creation of the `signer` could receive another function as one of its arguments that would implement how the password would be retrieved, so the test could contain a version of it where there would be not interaction with a user. Something like:

```
type reader func() ([]byte, error)

func (t *Tunnel) proxy() (net.Conn, error) {
  ...
  readPassword := func() ([]byte, error) {
    return terminal.ReadPassword(int(syscall.Stdin))
  }

  c, err := sshClientConfig(*t.server, readPassword)
  ...
}

func sshClientConfig(server Server, readPassword reader) (*ssh.ClientConfig, error) {
  ...
  signer := newSigner(key, readPassword)
  ...
}
```

So you could add a test that belongs to the `tunnel` package which would call `sshClientConfig.HostKeyCallback` and check if there is no error returned, otherwise fail the test.

Both private and public keys used on this test could be stored on `tunnel/testdata/dotssh`.
Look for function `prepareTestEnv()` on `tunnel/tunnel_test.go` to check how other files are getting prepared for the tests.

**Comment by davrodpin** [comment]
@akshaychhajed, please ignore my last comment. I hit submit without reloading the PR. 
I see your changes were mostly aligned with my comments. Good the we converged to the same solution 😄

**Comment by davrodpin** [comment]
Closing this pull request due to inactivity.
Will be opening a new one with the rest of the implementation making sure your commits are present.

Thank you for contributing to this project!

**Pull request closed without merging**
