### PR TITLE
Fix Build Error

### PR DESCRIPTION
**Pull request by shravan86**
uuid.New returns two values.

### CODE REVIEW

**Comment by davrodpin** [comment]
Hi @shravan86,

I am able to build mole using commit f633450 (the one before yours).
Could you provide the output of the following?

```
$ go env && go build github.com/davrodpin/mole/cmd/mole
```

**Comment by shravan86** [comment]
$ go env && go build github.com/davrodpin/mole/cmd/mole
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shravanambati/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shravanambati/Projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6m/xzz08dp57ql_ckhq6t1x6wvm0000gp/T/go-build705057524=/tmp/go-build -gno-record-gcc-switches -fno-common"
# github.com/davrodpin/mole/cmd/mole
github.com/davrodpin/mole/cmd/mole/main.go:206:22: multiple-value uuid.NewV4() in single-value context$ go env && go build github.com/davrodpin/mole/cmd/mole
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shravanambati/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shravanambati/Projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6m/xzz08dp57ql_ckhq6t1x6wvm0000gp/T/go-build705057524=/tmp/go-build -gno-record-gcc-switches -fno-common"
# github.com/davrodpin/mole/cmd/mole
github.com/davrodpin/mole/cmd/mole/main.go:206:22: multiple-value uuid.NewV4() in single-value context

**Comment by davrodpin** [comment]
Hi @shravan86,

Mole is now using the new [Go modules framework](https://blog.golang.org/using-go-modules) and I think you have it cloned under `$GOPATH`.
Could you move the project to a location outside `$GOPATH` then unset both `GOPATH` and `GOROOT` and try again?

**Comment by shravan86** [comment]
Hi @davrodpin, 

Yes if I unset the GOPATH, it builds fine. 
As you mentioned offline, I think with GOPATH it was looking for uuid library that is within GOPATH/pkg which is different from what was defined in go mod. Hence the API changed and caused a build error. 

I will remember to unset the GOPATH next time.

**Pull request closed without merging**
